package frame;

import dialog.Dialog;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;


public class Frame extends javax.swing.JFrame {
    
	private static final long serialVersionUID = 1L;
	private Dialog dialog;
	private boolean test = false;
	
	
    public Frame() {
    }
    
    public void initFrame() {
        initComponents();
    }
    
    public void setDialog(Dialog dialog) {
        this.dialog = dialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        activityListImportPanel = new javax.swing.JPanel();
        activityListPanel = new javax.swing.JPanel();
        label0 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activitiesList = new javax.swing.JList<>();
        importPanel = new javax.swing.JPanel();
        importButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        noActivityPanel = new javax.swing.JPanel();
        noActivityLabel = new javax.swing.JLabel();
        cyclingActivityPanel = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        cyclingDistanceLabel = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        cyclingAverageSpeedLabel = new javax.swing.JLabel();
        cyclingAltitudeUpLabel = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        cyclingTimeLabel = new javax.swing.JLabel();
        cyclingAltitudeGraphLabel = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        cyclingMaxSpeedLabel = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        cyclingAltitudeDownLabel = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        cyclingAverageAltitudeLabel = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        cyclingSpeedGraphLabel = new javax.swing.JLabel();
        cyclingTypeLabel = new javax.swing.JLabel();
        cyclingDateLabel = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        activityListImportPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        activityListImportPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activityListImportPanel.setPreferredSize(new java.awt.Dimension(274, 720));

        label0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label0.setText("Activités");

        jScrollPane1.setHorizontalScrollBar(null);

        activitiesList.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        activitiesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        activitiesList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activitiesList.setMaximumSize(new java.awt.Dimension(70, 120));
        activitiesList.setMinimumSize(new java.awt.Dimension(70, 120));
        activitiesList.setPreferredSize(new java.awt.Dimension(70, 120));
        activitiesList.setVisibleRowCount(6);
        activitiesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                activitiesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(activitiesList);

        importPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        importPanel.setPreferredSize(new java.awt.Dimension(324, 104));

        importButton.setText("Importer");
        importButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        importButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout importPanelLayout = new javax.swing.GroupLayout(importPanel);
        importPanel.setLayout(importPanelLayout);
        importPanelLayout.setHorizontalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        importPanelLayout.setVerticalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout activityListPanelLayout = new javax.swing.GroupLayout(activityListPanel);
        activityListPanel.setLayout(activityListPanelLayout);
        activityListPanelLayout.setHorizontalGroup(
            activityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(importPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        activityListPanelLayout.setVerticalGroup(
            activityListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityListPanelLayout.createSequentialGroup()
                .addComponent(label0, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout activityListImportPanelLayout = new javax.swing.GroupLayout(activityListImportPanel);
        activityListImportPanel.setLayout(activityListImportPanelLayout);
        activityListImportPanelLayout.setHorizontalGroup(
            activityListImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activityListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        activityListImportPanelLayout.setVerticalGroup(
            activityListImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activityListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        noActivityPanel.setPreferredSize(new java.awt.Dimension(1000, 720));

        noActivityLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        noActivityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noActivityLabel.setText("Veuillez selectionner une activité");
        noActivityLabel.setEnabled(false);
        noActivityLabel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout noActivityPanelLayout = new javax.swing.GroupLayout(noActivityPanel);
        noActivityPanel.setLayout(noActivityPanelLayout);
        noActivityPanelLayout.setHorizontalGroup(
            noActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noActivityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        noActivityPanelLayout.setVerticalGroup(
            noActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noActivityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cyclingActivityPanel.setBackground(new java.awt.Color(255, 255, 255));
        cyclingActivityPanel.setPreferredSize(new java.awt.Dimension(1000, 720));

        label7.setForeground(new java.awt.Color(102, 102, 102));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label7.setText("Temps");
        label7.setVerifyInputWhenFocusTarget(false);

        cyclingDistanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        cyclingDistanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingDistanceLabel.setText("00,00");
        cyclingDistanceLabel.setVerifyInputWhenFocusTarget(false);

        label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("km");
        label1.setVerifyInputWhenFocusTarget(false);

        label2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Altitude");
        label2.setVerifyInputWhenFocusTarget(false);

        label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("km/h");
        label3.setVerifyInputWhenFocusTarget(false);

        label4.setForeground(new java.awt.Color(102, 102, 102));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Vitesse moyenne");
        label4.setVerifyInputWhenFocusTarget(false);

        cyclingAverageSpeedLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingAverageSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingAverageSpeedLabel.setText("00,00");
        cyclingAverageSpeedLabel.setVerifyInputWhenFocusTarget(false);

        cyclingAltitudeUpLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingAltitudeUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingAltitudeUpLabel.setText("0");
        cyclingAltitudeUpLabel.setVerifyInputWhenFocusTarget(false);

        label5.setForeground(new java.awt.Color(102, 102, 102));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Gain d'altitude");
        label5.setVerifyInputWhenFocusTarget(false);

        label6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label6.setText("m");
        label6.setVerifyInputWhenFocusTarget(false);

        cyclingTimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        cyclingTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingTimeLabel.setText("00:00:00");
        cyclingTimeLabel.setVerifyInputWhenFocusTarget(false);

        cyclingAltitudeGraphLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingAltitudeGraphLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingAltitudeGraphLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\vince\\OneDrive\\Documents\\UT3\\ILU2\\PROJET\\2023-24-semestrep-ilu2-projet-VincentDubuisson\\ressources\\graph_no_activity.png")); // NOI18N
        cyclingAltitudeGraphLabel.setVerifyInputWhenFocusTarget(false);

        label8.setForeground(new java.awt.Color(102, 102, 102));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("Vitesse maximum");
        label8.setVerifyInputWhenFocusTarget(false);

        cyclingMaxSpeedLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingMaxSpeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingMaxSpeedLabel.setText("00,00");
        cyclingMaxSpeedLabel.setVerifyInputWhenFocusTarget(false);

        label9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("km/h");
        label9.setVerifyInputWhenFocusTarget(false);

        label10.setForeground(new java.awt.Color(102, 102, 102));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label10.setText("Perte d'altitude");
        label10.setVerifyInputWhenFocusTarget(false);

        cyclingAltitudeDownLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingAltitudeDownLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingAltitudeDownLabel.setText("0");
        cyclingAltitudeDownLabel.setVerifyInputWhenFocusTarget(false);

        label11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label11.setText("m");
        label11.setVerifyInputWhenFocusTarget(false);

        label12.setForeground(new java.awt.Color(102, 102, 102));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label12.setText("Altitude moyenne");
        label12.setVerifyInputWhenFocusTarget(false);

        cyclingAverageAltitudeLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingAverageAltitudeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingAverageAltitudeLabel.setText("0");
        cyclingAverageAltitudeLabel.setVerifyInputWhenFocusTarget(false);

        label13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText("m");
        label13.setVerifyInputWhenFocusTarget(false);

        label14.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText("Vitesse");
        label14.setVerifyInputWhenFocusTarget(false);

        cyclingSpeedGraphLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingSpeedGraphLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingSpeedGraphLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\vince\\OneDrive\\Documents\\UT3\\ILU2\\PROJET\\2023-24-semestrep-ilu2-projet-VincentDubuisson\\ressources\\graph_no_activity.png")); // NOI18N
        cyclingSpeedGraphLabel.setVerifyInputWhenFocusTarget(false);

        cyclingTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cyclingTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingTypeLabel.setText("Type");
        cyclingTypeLabel.setVerifyInputWhenFocusTarget(false);

        cyclingDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        cyclingDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cyclingDateLabel.setText("jj/mm/aaaa 00:00");
        cyclingDateLabel.setVerifyInputWhenFocusTarget(false);

        label15.setForeground(new java.awt.Color(102, 102, 102));
        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText("Distance totale");
        label15.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout cyclingActivityPanelLayout = new javax.swing.GroupLayout(cyclingActivityPanel);
        cyclingActivityPanel.setLayout(cyclingActivityPanelLayout);
        cyclingActivityPanelLayout.setHorizontalGroup(
            cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cyclingSpeedGraphLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cyclingAltitudeGraphLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                        .addComponent(cyclingAverageSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(226, 226, 226)
                                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                        .addComponent(cyclingMaxSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                        .addComponent(cyclingAverageAltitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(139, 139, 139)
                                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                        .addComponent(cyclingAltitudeUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(131, 131, 131)
                                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                        .addComponent(cyclingAltitudeDownLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18))
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cyclingTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cyclingDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                .addComponent(cyclingDistanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cyclingTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
        );
        cyclingActivityPanelLayout.setVerticalGroup(
            cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addComponent(cyclingTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cyclingDateLabel))
                    .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cyclingDistanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cyclingTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cyclingAverageSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cyclingMaxSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(cyclingSpeedGraphLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cyclingAltitudeUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cyclingAltitudeDownLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cyclingActivityPanelLayout.createSequentialGroup()
                        .addGroup(cyclingActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cyclingAverageAltitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cyclingAltitudeGraphLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1147, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(noActivityPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cyclingActivityPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noActivityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cyclingActivityPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noActivityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cyclingActivityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityListImportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(activityListImportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    
/* ========================================================================== */
/*                                LISTENERS                                   */
/* ========================================================================== */
    
    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        dialog.handleImportEvent();
    }
    
    private void activitiesListValueChanged(javax.swing.event.ListSelectionEvent evt) {                                            
        //Le code s'execute deux fois, je ne sais pas pourquoi donc j'ai bloquer pour qu'il ne se fasse qu'une fois
        if (!test) {
            int activity = activitiesList.getSelectedIndex();
            dialog.handleActivitiesListEvent(activity);
            
            test = true;
        } else {
            test = false;
        }
        
    }

    
/* ========================================================================== */
/*                                GETTEURS                                    */
/* ========================================================================== */

    public JButton getImportButton() {
        return importButton;
    }
    
    public JFileChooser getFileChooser() {
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Fichiers Excel (.xlsx)", "xlsx");
        fileChooser.setFileFilter(filter);
        
        return fileChooser;
    }
    
    public JList getActivitiesList() {
    	return activitiesList;
    }
    
    public JPanel getNoActivityPanel() {
        return noActivityPanel;
    }
    
    public JPanel getCyclingActivityPanel() {
        return cyclingActivityPanel;
    }
    
    public JLabel getCyclingTypeLabel() {
        return cyclingTypeLabel;
    }
    
    public JLabel getCyclingDateLabel() {
        return cyclingDateLabel;
    }
    
    public JLabel getCyclingDistanceLabel() {
        return cyclingDistanceLabel;
    }
    
    public JLabel getCyclingTimeLabel() {
        return cyclingTimeLabel;
    }
    
    public JLabel getCyclingAverageSpeedLabel() {
        return cyclingAverageSpeedLabel;
    }
    
    public JLabel getCyclingMaxSpeedLabel() {
        return cyclingMaxSpeedLabel;
    }
    
    public JLabel getCyclingSpeedGraphLabel() {
        return cyclingSpeedGraphLabel;
    }
    
    public JLabel getCyclingAverageAltitudeLabel() {
        return cyclingAverageAltitudeLabel;
    }
    
    public JLabel getCyclingAltitudeUpLabel() {
        return cyclingAltitudeUpLabel;
    }
    
    public JLabel getCyclingAltitudeDownLabel() {
        return cyclingAltitudeDownLabel;
    }
    
    public JLabel getCyclingAltitudeGraphLabel() {
        return cyclingAltitudeGraphLabel;
    }
    
    
/* ========================================================================== */
/*                               VARIABLES                                    */
/* ========================================================================== */

    // Variables declaration - do not modify                     
    private javax.swing.JList<String> activitiesList;
    private javax.swing.JPanel activityListImportPanel;
    private javax.swing.JPanel activityListPanel;
    private javax.swing.JPanel cyclingActivityPanel;
    private javax.swing.JLabel cyclingAltitudeDownLabel;
    private javax.swing.JLabel cyclingAltitudeGraphLabel;
    private javax.swing.JLabel cyclingAltitudeUpLabel;
    private javax.swing.JLabel cyclingAverageAltitudeLabel;
    private javax.swing.JLabel cyclingAverageSpeedLabel;
    private javax.swing.JLabel cyclingDateLabel;
    private javax.swing.JLabel cyclingDistanceLabel;
    private javax.swing.JLabel cyclingMaxSpeedLabel;
    private javax.swing.JLabel cyclingSpeedGraphLabel;
    private javax.swing.JLabel cyclingTimeLabel;
    private javax.swing.JLabel cyclingTypeLabel;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton importButton;
    private javax.swing.JPanel importPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel noActivityLabel;
    private javax.swing.JPanel noActivityPanel;
    // End of variables declaration                     
}
